services:
  ladon:
    image: ladon-ce
    restart: unless-stopped
    volumes:
      - "ladon-data:/root"
    ports:
      - "${APP_PORT}:8080"
volumes:
  ladon-data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${APP_VOLUME}"
